### ISSUE TITLE
Correção das consultas nas classes Servise e correção de parâmetros nas classes IService 

### ISSUE THREAD

**Issue by WedsonTeixeira** [marcosdosea/SOSCidadao#174]
mudança em todas consultas nas classes Service, a junção de tabelas serão feitas pelo próprio Entity framework:

Sugestão para correção de campos nulos de todas as classes que utilizam organização como dependência.

INSERT INTO `sos_cidadao`.`organizacao`
(`idOrganizacao`,
`cnpj`,
`nomeRazao`,
`nomeFantasia`,
`cep`,
`rua`,
`bairro`,
`cidade`,
`uf`,
`numeroEndereco`,
`dataRegistro`,
`idPessoa`)
VALUES
(1,
'00000000000000',
'Sem Organização',
'Sem Organização',
'0000000000',
'0',
'0',
'0',
'0',
0,
'20210101',
null);

**Comment by luizmoitinho** [comment]
Corrigindo a query: 
`INSERT INTO sos_cidadao.organizacao
(idOrganizacao,
cnpj,
nomeRazao,
nomeFantasia,
cep,
rua,
bairro,
cidade,
uf,
numeroEndereco,
dataRegistro,
idPessoa)
VALUES
(null,
'00000000000000',
'Sem Organização',
'Sem Organização',
'0000000000',
'0',
'0',
'0',
'0',
0,
'20210101',
null);`
