### ISSUE TITLE
Adicionar entidades para gerenciar o comentários nas ocorrencias

### ISSUE THREAD

**Issue by luizmoitinho** [marcosdosea/SOSCidadao#25]
Criar entidade, métodos, boundary e o que mais for preciso para que seja possivel adicionar comentarios em uma ocorrência, assim como é demonstrado nos protótipos.

**Comment by luizmoitinho** [comment]
Ao realizar novos teste, essa issue interferiu em uma ação que era pra ter sido feita em outra, por isso foi aberta novamente para que  possa ser corrigida.

**Comment by WedsonTeixeira** [comment]
Issue resolvida
